on: pull_request
name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run PHPCS inspection
        uses: docker://rtcamp/action-phpcs-code-review:v2.0.1
        env:
          SKIP_FOLDERS: "tests,.github"
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        with:
          args: "WordPress,WordPress-Core,WordPress-Docs"
